name: prepr_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  flutter:
    sdk: flutter
  table_calendar: ^3.1.1
  google_sign_in: ^6.2.1
  google_sign_in_ios: ^5.7.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:
  uses-material-design: true
  assets:
    - assets/GoogleIcon.png